# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wyk/EvenOdd

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wyk/EvenOdd/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wyk/EvenOdd/build/CMakeFiles /home/wyk/EvenOdd/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wyk/EvenOdd/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named time_check

# Build rule for target.
time_check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 time_check
.PHONY : time_check

# fast build rule for target.
time_check/fast:
	$(MAKE) -f CMakeFiles/time_check.dir/build.make CMakeFiles/time_check.dir/build
.PHONY : time_check/fast

#=============================================================================
# Target rules for targets named evenoddlib

# Build rule for target.
evenoddlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 evenoddlib
.PHONY : evenoddlib

# fast build rule for target.
evenoddlib/fast:
	$(MAKE) -f CMakeFiles/evenoddlib.dir/build.make CMakeFiles/evenoddlib.dir/build
.PHONY : evenoddlib/fast

#=============================================================================
# Target rules for targets named evenodd

# Build rule for target.
evenodd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 evenodd
.PHONY : evenodd

# fast build rule for target.
evenodd/fast:
	$(MAKE) -f CMakeFiles/evenodd.dir/build.make CMakeFiles/evenodd.dir/build
.PHONY : evenodd/fast

decoding.o: decoding.cpp.o

.PHONY : decoding.o

# target to build an object file
decoding.cpp.o:
	$(MAKE) -f CMakeFiles/evenoddlib.dir/build.make CMakeFiles/evenoddlib.dir/decoding.cpp.o
.PHONY : decoding.cpp.o

decoding.i: decoding.cpp.i

.PHONY : decoding.i

# target to preprocess a source file
decoding.cpp.i:
	$(MAKE) -f CMakeFiles/evenoddlib.dir/build.make CMakeFiles/evenoddlib.dir/decoding.cpp.i
.PHONY : decoding.cpp.i

decoding.s: decoding.cpp.s

.PHONY : decoding.s

# target to generate assembly for a file
decoding.cpp.s:
	$(MAKE) -f CMakeFiles/evenoddlib.dir/build.make CMakeFiles/evenoddlib.dir/decoding.cpp.s
.PHONY : decoding.cpp.s

encoding.o: encoding.cpp.o

.PHONY : encoding.o

# target to build an object file
encoding.cpp.o:
	$(MAKE) -f CMakeFiles/evenoddlib.dir/build.make CMakeFiles/evenoddlib.dir/encoding.cpp.o
.PHONY : encoding.cpp.o

encoding.i: encoding.cpp.i

.PHONY : encoding.i

# target to preprocess a source file
encoding.cpp.i:
	$(MAKE) -f CMakeFiles/evenoddlib.dir/build.make CMakeFiles/evenoddlib.dir/encoding.cpp.i
.PHONY : encoding.cpp.i

encoding.s: encoding.cpp.s

.PHONY : encoding.s

# target to generate assembly for a file
encoding.cpp.s:
	$(MAKE) -f CMakeFiles/evenoddlib.dir/build.make CMakeFiles/evenoddlib.dir/encoding.cpp.s
.PHONY : encoding.cpp.s

evenodd.o: evenodd.cpp.o

.PHONY : evenodd.o

# target to build an object file
evenodd.cpp.o:
	$(MAKE) -f CMakeFiles/evenodd.dir/build.make CMakeFiles/evenodd.dir/evenodd.cpp.o
.PHONY : evenodd.cpp.o

evenodd.i: evenodd.cpp.i

.PHONY : evenodd.i

# target to preprocess a source file
evenodd.cpp.i:
	$(MAKE) -f CMakeFiles/evenodd.dir/build.make CMakeFiles/evenodd.dir/evenodd.cpp.i
.PHONY : evenodd.cpp.i

evenodd.s: evenodd.cpp.s

.PHONY : evenodd.s

# target to generate assembly for a file
evenodd.cpp.s:
	$(MAKE) -f CMakeFiles/evenodd.dir/build.make CMakeFiles/evenodd.dir/evenodd.cpp.s
.PHONY : evenodd.cpp.s

log.o: log.cpp.o

.PHONY : log.o

# target to build an object file
log.cpp.o:
	$(MAKE) -f CMakeFiles/evenoddlib.dir/build.make CMakeFiles/evenoddlib.dir/log.cpp.o
.PHONY : log.cpp.o

log.i: log.cpp.i

.PHONY : log.i

# target to preprocess a source file
log.cpp.i:
	$(MAKE) -f CMakeFiles/evenoddlib.dir/build.make CMakeFiles/evenoddlib.dir/log.cpp.i
.PHONY : log.cpp.i

log.s: log.cpp.s

.PHONY : log.s

# target to generate assembly for a file
log.cpp.s:
	$(MAKE) -f CMakeFiles/evenoddlib.dir/build.make CMakeFiles/evenoddlib.dir/log.cpp.s
.PHONY : log.cpp.s

repair.o: repair.cpp.o

.PHONY : repair.o

# target to build an object file
repair.cpp.o:
	$(MAKE) -f CMakeFiles/evenoddlib.dir/build.make CMakeFiles/evenoddlib.dir/repair.cpp.o
.PHONY : repair.cpp.o

repair.i: repair.cpp.i

.PHONY : repair.i

# target to preprocess a source file
repair.cpp.i:
	$(MAKE) -f CMakeFiles/evenoddlib.dir/build.make CMakeFiles/evenoddlib.dir/repair.cpp.i
.PHONY : repair.cpp.i

repair.s: repair.cpp.s

.PHONY : repair.s

# target to generate assembly for a file
repair.cpp.s:
	$(MAKE) -f CMakeFiles/evenoddlib.dir/build.make CMakeFiles/evenoddlib.dir/repair.cpp.s
.PHONY : repair.cpp.s

time_check.o: time_check.cpp.o

.PHONY : time_check.o

# target to build an object file
time_check.cpp.o:
	$(MAKE) -f CMakeFiles/time_check.dir/build.make CMakeFiles/time_check.dir/time_check.cpp.o
.PHONY : time_check.cpp.o

time_check.i: time_check.cpp.i

.PHONY : time_check.i

# target to preprocess a source file
time_check.cpp.i:
	$(MAKE) -f CMakeFiles/time_check.dir/build.make CMakeFiles/time_check.dir/time_check.cpp.i
.PHONY : time_check.cpp.i

time_check.s: time_check.cpp.s

.PHONY : time_check.s

# target to generate assembly for a file
time_check.cpp.s:
	$(MAKE) -f CMakeFiles/time_check.dir/build.make CMakeFiles/time_check.dir/time_check.cpp.s
.PHONY : time_check.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... time_check"
	@echo "... evenoddlib"
	@echo "... evenodd"
	@echo "... decoding.o"
	@echo "... decoding.i"
	@echo "... decoding.s"
	@echo "... encoding.o"
	@echo "... encoding.i"
	@echo "... encoding.s"
	@echo "... evenodd.o"
	@echo "... evenodd.i"
	@echo "... evenodd.s"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... repair.o"
	@echo "... repair.i"
	@echo "... repair.s"
	@echo "... time_check.o"
	@echo "... time_check.i"
	@echo "... time_check.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

